version: '3'

volumes:
  data_ui:
  data_attachments:
  data_webassets:

services:

  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    command: --log-facility=-
    cap_add:
       - NET_ADMIN
    ports:
      - 172.17.0.1:53:53/tcp
      - 172.17.0.1:53:53/udp
    links:
      - proxy:specify6.bioatlas.se
      - proxy:specify7.bioatlas.se
      - proxy:reports.bioatlas.se
      - proxy:media.bioatlas.se

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
  
  db:
    image: mysql:5.7
    env_file: .env
    volumes:
      - ./s6init.sql:/docker-entrypoint-initdb.d/s6init.sql
      - ./data.sql:/tmp/data.sql
      - ./create_schema.sh:/docker-entrypoint-initdb.d/create_schema.sh

  media:
    image: bioatlas/assetserver:latest
    environment:
      - VIRTUAL_HOST=media.bioatlas.se
      - VIRTUAL_PORT=8080
    volumes:
      - ./AttachmentStorage:/root/Specify/AttachmentStorage

  report:
    image: bioatlas/reportserver:latest
    environment:
      - VIRTUAL_HOST=reports.bioatlas.se
      - VIRTUAL_PORT=8080
    volumes:
      - data_ui:/opt/Specify
      - ./report-server/m2:/root/.m2

  ui:
    image: bioatlas/specify-desktop:v6.7.01
    volumes:
      - data_ui:/opt/Specify
      - ./user.properties:/root/Specify/user.properties
      - ./AttachmentStorage:/root/Specify/AttachmentStorage
    depends_on:
      - db
      - report
      - media

  as:
    image: bioatlas/specify-server:v7
    volumes:
      - data_ui:/opt/Specify
      - data_webassets:/code/specifyweb/frontend
      - ./specify_settings.py:/code/specifyweb/settings/specify_settings.py
    depends_on:
      - db
      - report
      - media

  wssix:
    image: nginx:alpine
    volumes:
      - data_ui:/opt/Specify
      - data_webassets:/code/specifyweb/frontend
      - ./six.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=specify6.bioatlas.se
    depends_on:
      - ui

  wsseven:
    image: nginx:alpine
    volumes:
      - data_ui:/opt/Specify
      - data_webassets:/code/specifyweb/frontend
      - ./seven.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=specify7.bioatlas.se
    depends_on:
      - as

