version: '2'

services:

  fs:
    image: tianon/true
    volumes:      
      - /tmp/.X11-unix/X0:/tmp/.X11-unix/X0
  
  db:
    image: mysql:5.7
    env_file: .env
    volumes:
      - ./s6init.sql:/docker-entrypoint-initdb.d/s6init.sql
      - ./data.sql:/tmp/data.sql
      - ./create_schema.sh:/docker-entrypoint-initdb.d/create_schema.sh
    ports:
      - 3306:3306

  media:
    image: dina/assetserver:latest
    volumes:
      - ./AttachmentStorage:/root/Specify/AttachmentStorage

  ui:
    image: dina/specify-desktop:v6.6.05
    command: Specify
    environment:
      - DISPLAY=$DISPLAY
    volumes_from:
      - fs
    volumes:
      - ./user.properties:/root/Specify/user.properties
      - ./AttachmentStorage:/root/Specify/AttachmentStorage

  report:
    image: dina/reportserver:latest
    volumes_from:
      - ui
    volumes:
      - ./report-server/m2:/root/.m2

  as:
    image: dina/specify-server:v7
    volumes_from:
      - ui
    volumes:
      - ./specify_settings.py:/code/specifyweb/settings/specify_settings.py

  ws:
    image: nginx:alpine
    volumes_from:
      - ui
      - as
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"

